name: Delete artifact

on:
  workflow_run:
    workflows: [Artifacts]
    types:
      - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - id: cleanup_artifacts
        name: cleanup artifacts
        shell: powershell
        run: |
          .\cleanup_artifacts.ps1 -github_token ${{ secrets.GITHUB_TOKEN }}
      
