name: Delete artifact

on: workflow_dispatch
  #workflow_run:
    #workflows: [Artifacts]
   # types:
     # - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
        
      - id: cleanup_artifacts
        name: cleanup artifacts
        shell: powershell
        run: |
          .\powershell\cleanup_artifacts.ps1 -github_token ${{ secrets.GITHUB_TOKEN }}
      
