name: Delete artifact

on:
  workflow_run:
    workflows: [Artifacts]
    types:
      - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: 'Delete artifacts'
        shell: pwsh
        run: .\powershell\cleanup_artifacts.ps1 -github_token ${{ secrets.GITHUB_TOKEN }}
      
