name: Download data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - id: download_artifact
        name: download artifact
        shell: powershell
        run: |
          .\powershell\download_artifact.ps1 -github_token ${{ secrets.GITHUB_TOKEN }}   
                      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .\

      - name: Display structure of downloaded files again
        run: ls -R
        working-directory: D:\
          
      - name: Copy file
        shell: powershell
        run: |
          Copy-Item -Path "D:\a\GitHubActionsDemo\GitHubActionsDemo\test" -Destination "D:\a\GitHubActionsDemo\GitHubActionsDemo\new_folder" -Recurse
      
      - name: Display structure of downloaded files again
        run: ls -R
        working-directory: D:\a\GitHubActionsDemo\GitHubActionsDemo\new_folder
         
      
