name: Download data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      #- id: download_artifact
      #  name: download artifact
      #  shell: powershell
      #  run: |
      #    .\powershell\download_artifact.ps1 -github_token ${{ secrets.GITHUB_TOKEN }}   
     
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2          
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: upload_artifact.yml
            
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .\
          
      - name: Copy file
        shell: powershell
        run: |
          Copy-Item D:\a\GitHubActionsDemo\GitHubActionsDemo\test\math-homework.txt -Destination "D:\a\GitHubActionsDemo\GitHubActionsDemo\new_folder"
      
      - name: Display structure of downloaded files again
        run: ls -R
        working-directory: D:\a\GitHubActionsDemo\GitHubActionsDemo\new_folder
         
      
