name: Download data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      #- id: download_artifact
      #  name: download artifact
      #  shell: powershell
      #  run: |
      #    .\powershell\download_artifact.ps1 -github_token ${{ secrets.GITHUB_TOKEN }}   
     
      - id: download
        uses: actions/download-artifact@v3
        with:
          path: path/to/artifacts

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifacts
          
          
      - id: copy_file
        name: copy file
        #shell: powershell
        #run: |
         
      
