name: Download data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/download-artifact@v3
        with:
          name: test
          path: path/to/artifact
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact
          
          
      - id: copy_file
        name: copy file
        shell: powershell
        run: |
         ls ${{github.workspace}}\path\to\artifact
      
