name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "triggered by: ${{ github.event_name }}"
          echo "branch: ${{github.ref}}"
      - name: list all files in repo
        run: |
          echo "repository ${{ github. repository }} contains:"
          tree
      
    
    
