name: Upload data

on: push

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt          
          tar -cvzf math-homework.tar ./
          
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.tar
  
  
