name: Upload data

on: push

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > in.txt         
      - shell: bash
        run: |
          tar.exe -a -c -f out.zip in.txt
          
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out.zip
  
  
